name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  chapel-run-function:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
      # env:
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - name: Install Python, pip, and Python libraries
        run: |
          apt update
          apt install --no-cache-dir -y python3.12
          python3 --version
          pip3 install --no-cache-dir -y python3-pip
          pip3 install --no-cache-dir -y numpy 
          pip3 install --no-cache-dir -y torch 
          pip3 install --no-cache-dir -y torchvision
          pip3 install --no-cache-dir -y virtualenv
      - uses: actions/checkout@v4
      - name: Check for dockerenv file and Python version
        run: |
          ls /.dockerenv && echo Found dockerenv
          echo "No dockerenv"
          python3 --version || echo "Python not found!"
      - name: Compile example/vgg
        run: |
          (cd examples/vgg && chpl test.chpl -M ../../src -M ../../lib -o vgg && python3 dump_weights.py && python3 process_img.py imgs/frog.jpg && ./vgg imgs/frog.chdata)
      - name: Run correspondence tests
        run: |
          (cd test/correspondence && python3 correspondence.py) || echo "Wups! Correspondence bug or more likely test failure!"
      - name:
        run: |
          echo "Pau!"