name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  chapel-run-function:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
      # env:
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    steps:
      - uses: actions/checkout@v4
      - name: Check for dockerenv file
        run: |
          ls /.dockerenv && echo Found dockerenv
          echo "No dockerenv"
      - name: Compile example/vgg
        run: |
          cd examples/vgg && chpl test.chpl -M ../../src -M ../../lib -o vgg
      - name:
        run: |
          echo "Pau!"